import Toybox.Application;
import Toybox.Lang;
import Toybox.StringUtil;

// Source used to create an asset
// Each `AudioResource` should represent a single provider - e.g. Soundcloud, Plex, Youtube
class AudioResource {
    var href as String;
    var id as String;

    function initialize(href as String, options as { :id as String }) {
        self.href = href;
        self.id = options[:id] as String;
    }

    function getId() as String {
        return self.id;
    }

    function getTitle() as String {
        // parse href for filename - not really an options no regexp/slow devices
        // should be done in initialize()
        var title = self.href.toCharArray().reverse();
        var split = StringUtil.charArrayToString(title).find("/");

        if (split != null) {
            title = title.slice(0, split).reverse();
        }
        title = StringUtil.charArrayToString(title);

        // return "TITLE " + self.id;
        return title;
    }

    function toStorage() as PersistableType {
        return {
            "href" => self.href,
            "id" => getId()
        };
    }
}

function getAudioResources() as Array<AudioResource> {
    return [
        new AudioResource("https://getsamplefiles.com/download/m4a/sample-3.m4a", {
            :id => "id-1"
        }),
        new AudioResource("https://github.com/supermihi/pytaglib/raw/refs/heads/main/tests/data/issue46.m4a", {
            :id => "id-99"
        }),
        new AudioResource("http://192.168.1.222:8001/BBC/The_Ravers_Hour_-_Aho_Ssan_in_the_Mix_m001rrfl_original.m4a", {
            :id => "uluru-99"
        })
    ];
}

function getUluruAudio() as Array<AudioResource> {
    var loadedFromService = [
        // "./Eats Everything - Radio 1's Essential Mix (2023-09-02).mp3",
        "/BBC/Mary_Anne_Hobbs_-_HAAi_with_the_ICONS_Mix_m001rz45_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Karen_Nyame_KG_with_the_ICONS_MIX_m001rrf4_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Metalheadz_30_ICONS_Mix_m001r8gm_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Sofia_Kourtesis_with_the_ICONS_Mix_m001rg4k_original.m4a",
        "./BBC/Radio_1s_Classic_Essential_Mix_-_Avalon_Emerson_2018_m001rwk1_original.m4a",
        "./BBC/Radio_1s_Classic_Essential_Mix_-_Ben_Klock_2015_m001rn8r_original.m4a",
        "./BBC/Radio_1s_Classic_Essential_Mix_-_Pan-Pot_2017_m001s35c_original.m4a",
        "./BBC/Radio_1s_Classic_Essential_Mix_-_X-Press_2_2002_m001rg0w_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_ARTBAT_m001rwrz_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Barry_Cant_Swim_m001r708_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_CamelPhat_m001q5xw_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_DJ_HEARTSTRING_m001rn58_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_DJ_Nobu_m001rfnc_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Dom_Dolla_m001qs3v_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Eats_Everything_m001prdg_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Eliza_Rose_m001qklk_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Massano_m001qcr0_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Pangaea_m001qzws_original.m4a",
        "./BBC/Radio_1s_Residency_-_BAMBII_-_Festival_Bangers_m001plth_original.m4a",
        "./BBC/Radio_1s_Residency_-_Ben_Hemsley_at_Boardmasters_m001pr7w_original.m4a",
        "./BBC/Radio_1s_Residency_-_Carl_Cox_-_Drum_Bass_special_m000wxyv_original.m4a",
        "./BBC/Radio_1s_Residency_-_Conducta_-_Eat_my_edit_m001qkjw_original.m4a",
        "./BBC/Radio_1s_Residency_-_Conducta_-_House_and_garage_special_m001qcpc_original.m4a",
        "./BBC/Radio_1s_Residency_-_Conducta_-_Introduction_m001pxxx_original.m4a",
        "./BBC/Radio_1s_Residency_-_Conducta_-_Take_a_break_Breakbeat_special_m001q5wv_original.m4a",
        "./BBC/Radio_1s_Residency_-_DJ_Tennis_-_Dream_and_Italo_house_m001rfjt_original.m4a",
        "./BBC/Radio_1s_Residency_-_DJ_Tennis_-_Italo_disco_m001qs5y_original.m4a",
        "./BBC/Radio_1s_Residency_-_DJ_Tennis_-_Punk_and_electronic_music_m001r722_original.m4a",
        "./BBC/Radio_1s_Residency_-_DJ_Tennis_-_Synth_pop_m001qzs1_original.m4a",
        "./BBC/Radio_1s_Residency_-_I._JORDAN_at_Boardmasters_m001pr82_original.m4a",
        "./BBC/Radio_1s_Residency_-_La_La_-_All_killer_no_filler_m001qcp7_original.m4a",
        "./BBC/Radio_1s_Residency_-_La_La_-_An_introduction_m001pxxs_original.m4a",
        "./BBC/Radio_1s_Residency_-_La_La_-_Mixed_bag_m001q5ws_original.m4a",
        "./BBC/Radio_1s_Residency_-_La_La_-_The_grand_finale_m001qkjb_original.m4a",
        "./BBC/Radio_1s_Residency_-_Manuka_Honey_-_Slow_and_hardcore_m001rfk6_original.m4a",
        "./BBC/Radio_1s_Residency_-_Manuka_Honey_-_The_beginning_m001qs60_original.m4a",
        "./BBC/Radio_1s_Residency_-_Manuka_Honey_Hybridity_m001qzs5_original.m4a",
        "./BBC/Radio_1s_Residency_-_Manuka_Honey_Sounds_from_across_the_world_m001r724_original.m4a",
        "./BBC/Radio_1s_Residency_-_Moxie_-_The_dub_mix_m001pltc_original.m4a",
        "./BBC/Radio_1s_Residency_-_Paula_Tape_-_Electronic_house_m001rxsn_original.m4a",
        "./BBC/Radio_1s_Residency_-_Paula_Tape_-_Tribal_house_m001rn3c_original.m4a",
        "./BBC/SHERELLE_-_Babes_its_jet_lag_szn_m001s2q8_original.m4a",
        "./BBC/SHERELLE_-_Deep_Dive_Loraine_James_m001rfz2_original.m4a",
        "./BBC/SHERELLE_-_Deep_Dive_Tim_Reaper_m001ryv7_original.m4a",
        "./BBC/SHERELLE_-_Eh_Wut_m001qv3d_original.m4a",
        "./BBC/SHERELLE_-_Gal_No_Worry_m001qngf_original.m4a",
        "./BBC/SHERELLE_-_No_one_does_it_like_they_do_m001r2kg_original.m4a",
        "./BBC/SHERELLE_-_Slow_It_Down_Speed_It_Up_m001r93v_original.m4a",
        "./BBC/SHERELLE_-_Sweet_Fantasy_m001rr84_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Bored_Lord_in_the_mix_m001qw54_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_C.FRIM_in_the_mix_m001r2kj_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_DJ_Storm_in_the_mix_m001rfz4_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Darwin_in_the_mix_m001s2qf_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Dinamarca_in_the_mix_m001qw5s_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_I._JORDAN_in_the_mix_m001qw58_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Luke_Vibert_as_Amen_Andrews_Halloween_Special_m001rr88_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Regal86_in_the_mix_m001r94b_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Tim_Reaper_in_the_mix_m001ryvs_original.m4a",
        "./BBC/The_Blessed_Madonna_-_See_you_ravers_on_the_radio_m001pzp3_original.m4a",
        "./BBC/The_Blessed_Madonna_-_The_Doomsday_Playlist_-_Part_1_m001pznz_original.m4a",
        "./BBC/The_Blessed_Madonna_-_The_Doomsday_Playlist_-_Part_2_m001pzp1_original.m4a",
        "./BBC/The_Ravers_Hour_-_Aho_Ssan_in_the_Mix_m001rrfl_original.m4a",
        "./BBC/The_Ravers_Hour_-_DJ_ADHD_in_the_Mix_m001qvcw_original.m4a",
        "./BBC/The_Ravers_Hour_-_Honeydrip_in_the_Mix_m001rg50_original.m4a",
        "./BBC/The_Ravers_Hour_-_Mndsgn_in_the_Mix_m001qn2k_original.m4a",
        "./BBC/The_Ravers_Hour_-_Schlachthofbronx_in_the_Mix_m001r8h2_original.m4a",
        "./BBC/The_Ravers_Hour_-_Scuba_in_the_Mix_m001r2bp_original.m4a",
        "./BBC/The_Ravers_Hour_-_patten_in_the_Mix_m001rz5n_original.m4a",
        "./BBC/The_Ravers_Hour_-_DJ_Murdadawg_in_the_Mix_m001s2sz_original.m4a",
        "./BBC/The_Ravers_Hour_-_BASHKKA_in_the_Mix_m001sdkn_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Moxie_with_the_ICONS_Mix_m001s2s2_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_With_the_ICONS_Mix_m001sdk6_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Half_Queen_in_the_mix_m001sd9k_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_TSVI_all_production_mix_m001sn33_original.m4a",
        "./BBC/The_Ravers_Hour_-_Samizdat_in_the_Mix_m001sn6l_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Chloe_Robinson_with_the_ICONS_Mix_m001sn64_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Nick_Leon_in_the_mix_m001stwf_original.m4a",
        "./BBC/The_Ravers_Hour_-_Meg_Ward_in_the_Mix_m001st9c_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Krust_with_the_ICONS_Mix_m001st8x_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_DJ_Phil_in_the_mix_m001szxd_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_D4_D4NCE_Duck_Sauce_m001r70g_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_D4_D4NCE_J.Worra_m001rfnf_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_CRUCAST_IVY_m001rws1_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_CRUCAST_Darkzy_m001s3b8_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_CRUCAST_Skepsis_m001sb5r_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_FFRR_Aaron_Hibell_m001sjr3_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_FFRR_The_Blessed_Madonna_m001ssr2_original.m4a",
        "./BBC/The_Ravers_Hour_-_DJ_Haram_in_the_Mix_m001t0g0_original.m4a",
        "./BBC/The_Ravers_Hour_-_glue70_in_the_Mix_m001tk6w_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Stenny_with_the_ICONS_Mix_m001t0d9_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Bicep_with_the_ICONS_Mix_m001tb55_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_With_the_ICONS_Mix_m001tk6f_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Alix_Perez_in_the_mix_m001t9v2_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_C_R_R_D_R_in_the_mix_m001tj4y_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_FFRR_Parisi_m001t0nb_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_FFRR_Kenya_Grace_m001t720_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_FFRR_Diplo_m001tk5z_original.m4a",
        "./BBC/The_Ravers_Hour_-_LOUFR_in_the_mix_m001xmvd_original.m4a",
        "./BBC/The_Ravers_Hour_-_Samurai_Breaks_in_the_mix_m001xw2z_original.m4a",
        "./BBC/The_Ravers_Hour_-_Marie_Montexier_Vinyl_Special_m001y383_original.m4a",
        "./BBC/The_Ravers_Hour_-_Son_of_Philip_in_the_mix_m001y9c3_original.m4a",
        "./BBC/The_Ravers_Hour_-_Big_Dope_P_in_the_mix_m001yh44_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Four_Tet_with_the_ICONS_Mix_m001y9bn_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Helena_Hauff_with_the_ICONS_Mix_m001yh3p_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Heavee_m001xw9m_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Nick_Leon_m001y31z_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_SONIKKU_m001y95b_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Machinedrum_m001ygsm_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Manuka_Honey_m001yr3m_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Defected_Records_Darius_Syrossian_Olive_F_m001ww0c_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Defected_Records_Monki_m001x39m_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Defected_Records_YOURS_m001xbrf_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Drumsheds_Prospa_m001xkf2_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Drumsheds_Ben_Hemsley_m001xsw9_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Drumsheds_Airrica_m001y09l_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Drumsheds_SYREETA_m001y6mn_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Anjunabeats_Above_Beyond_m001ydv7_original.m4a",
        "./BBC/The_Ravers_Hour_-_sideproject_in_the_mix_m0021c1d_original.m4a",
        "./BBC/The_Ravers_Hour_-_Facta_in_the_mix_m0021hvj_original.m4a",
        "./BBC/The_Ravers_Hour_-_All_Points_East_Special_m0021q2t_original.m4a",
        "./BBC/The_Ravers_Hour_-_Leevisa_in_the_Mix_m0021wmx_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_SBTRKT_m0021jnk_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Melle_Brown_m0021qyt_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Stones_Taro_m0021y0j_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_MJ_Cole_m00221b7_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Glastonbury_2024_Eats_Everything_B2B_Groove_Armada_m0020fl6_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Glastonbury_2024_Enzo_Siragusa_m0020mrm_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Glastonbury_2024_Friction_B2B_K_Motionz_m0020vh6_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Glastonbury_2024_ALISHA_B2B_Archie_Hamilton_m00212bw_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Ibiza_2024_LF_System_m00218lh_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Ibiza_2024_TSHA_m0021frl_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Ibiza_2024_Mousse_T._m0021mnw_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Ibiza_2024_Andrea_Oliva_B2B_John_Summit_m0021tpc_original.m4a",
        "./BBC/The_Ravers_Hour_-_Violence_Gratuite_in_the_Mix_m00221mf_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Catching_Cairo_m00228q9_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Ibiza_2024_Horse_Meat_Disco_m002251x_original.m4a",
        "./BBC/The_Ravers_Hour_-_DJ_Stingray_313_In_The_Mix_m00228t8_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_VXRGO_m0022hn9_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Fabric_p-rallel_m00229hg_original.m4a",
        "./BBC/The_Ravers_Hour_-_Martyn_Bootyspoon_in_the_mix_m0022hx6_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Lara_Jones_with_the_ICONS_Mix_m0022hwr_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Ivy_Lab_m0022pyh_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Fabric_Yung_Singh_m0022hw9_original.m4a",
        "./BBC/The_Ravers_Hour_-_Avneesh_in_the_mix_m0022q87_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Kloke_m00230dc_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Fabric_Peach_m0022s31_original.m4a",
        "./BBC/The_Ravers_Hour_-_Low_End_Activist_in_the_mix_m0022zrf_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Djrum_with_the_ICONS_Mix_m0022zqz_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Madam_X_m00234g5_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Fabric_Terry_Francis_m0022xxg_original.m4a",
        "./BBC/The_Ravers_Hour_-_Maroki_in_the_Mix_m00234mg_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Ariel_Zetina_m0023fyx_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Timewarp_Nina_Kraviz_m002360h_original.m4a",
        "./BBC/The_Ravers_Hour_-_fka.m4a_in_the_mix_m0023f86_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_DJ_Oblig_m0023nzl_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Time_Warp_Sven_Vath_m0023d20_original.m4a",
        "./BBC/The_Ravers_Hour_-_Nego0_in_the_mix_m0023p8b_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Kelly_Lee_Owens_with_the_ICONS_Mix_m0023p7w_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Byrell_The_Great_m0023w5r_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Time_Warp_Mochakk_m0023lrw_original.m4a",
        "./BBC/The_Ravers_Hour_-_Isaka_in_the_Mix_m0023wbq_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Quiet_Husband_with_the_ICONS_Mix_m0023wb8_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Spooky_Bizzle_m00245rm_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Time_Warp_Clara_Cuve_m0023tms_original.m4a",
        "./BBC/The_Ravers_Hour_-_Etch_in_the_Mix_m00245y9_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_dBridge_with_the_ICONS_Mix_m00245xv_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Sam_Binga_m0024fvt_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Aus_Music_Amy_Dabbs_m00242pt_original.m4a",
        "./BBC/The_Ravers_Hour_-_Bell_Curve_in_the_Mix_m0024dx8_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Adam_F_with_the_ICONS_Mix_m0024dwt_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Aus_Music_Quantic_m0024cfg_original.m4a",
        "./BBC/The_Ravers_Hour_-_DNGDNGDNG_in_the_mix_m0024mdq_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_EMA_with_the_ICONS_Mix_m0024md8_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Chippy_Nonstop_m0024m8z_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Conducta_m0024xhm_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Aus_Music_Dam_Swindle_m0024kk4_original.m4a",
        "./BBC/The_Ravers_Hour_-_Erotic_Cafe_in_the_mix_m0024wwc_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Mantra_with_the_ICONS_Mix_m0024wvx_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Ell_Murphy_m002556d_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Aus_Music_Cinthie_m0024xdb_original.m4a",
        "./BBC/The_Ravers_Hour_-_Sakura_Tsuruta_in_the_mix_m00254t2_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Aus_Music_Will_Saul_m002523j_original.m4a",
        "./BBC/The_Ravers_Hour_-_Rose_Again_in_the_mix_m0025c8z_original.m4a",
        "./BBC/The_Ravers_Hour_-_Madison_Willing_in_the_mix_m0025lk5_original.m4a",
        "./BBC/The_Ravers_Hour_-_Toms_Extended_Yuletide_Mix_m0025tdq_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Radioactive_Man_with_the_ICONS_Mix_m0025c8j_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Pet_Shop_Boys_with_the_ICONS_Mix_m0025ljq_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Flore_m0025cwk_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_TYGAPAW_m0025mtx_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Emerald_m0025w45_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Jeremiah_Asiamah_m002628n_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Helix_Records_edd_m00258nr_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_UKF_15_Years_m0025jms_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Good_Company_ZDS_and_Jess_Bays_m0025r79_original.m4a",
        "./BBC/The_Ravers_Hour_-_Legowelt_in_the_mix_m00262sm_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Anjunabeats_Amy_Wiles_m001yw0s_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Kia_m00262qr_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Pricila_Diaz_m00262qt_original.m4a",
        "./BBC/The_Ravers_Hour_-_Coco_Em_m0026b76_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Pete_Cannon_m00269vb_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_livwutang_m00267c1_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Tatyana_Jane_m00267c3_original.m4a",
        "./BBC/The_Ravers_Hour_-_TSVI_in_the_mix_m0026l4p_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Lukid_m0026kr2_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_CCL_m0026mk2_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_MJK_m0026l1x_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Spectral_m0026l1z_original.m4a",
        "./BBC/The_Ravers_Hour_-_Nocow_in_the_mix_m0026scl_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Tips_for_2025_-_Bun_Xapa_m0026s9q_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Tips_for_2025_-_Hardt_Antoine_m0026s9s_original.m4a",
        "./BBC/The_Ravers_Hour_-_KUCKA_in_the_mix_m00270m0_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_with_Fabio_Grooverider_m0026wgt_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_with_Fabio_Grooverider_m0027546_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Tips_for_2025_-_Azzecca_m00270n1_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Tips_for_2025_-_Minna-no-kimochi_m00270n3_original.m4a",
        "./BBC/The_Ravers_Hour_-_Muadeep_in_the_mix_m00275h4_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Blawan_with_the_ICONS_Mix_m00275gp_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_with_HAAi_m0027bx7_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_POSITIVA_Alex_Wann_m00273yx_original.m4a",
        "./eventually-acid-peng.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - Imagination.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - Imagination.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - My Lyf.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - Conflict VIP.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - Switch Down.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - Tutorial.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - Ease The Pain VIP.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - My Lyf.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - Conflict VIP.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - Switch Down.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - Tutorial.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - Ease The Pain VIP.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/In My Arms ( Acapella ).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/In My Arms ( Acapella ).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Atmosphere (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Conversation (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Win The Game ( Acapella ).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Move LikeThat (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Energy (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/See It Through My Eyes (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Body (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Worry Bout Them (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/That That That (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Stay With Me (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Atmosphere (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Conversation (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Win The Game ( Acapella ).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Move LikeThat (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Energy (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/See It Through My Eyes (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Body (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Worry Bout Them (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/That That That (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Stay With Me (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/Lawrence James - Hold You In My Arms.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/Lawrence James - Hold You In My Arms.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/MAFX - zap.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/Lawrence James - That That That.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/Lawrence James - Conversation.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/Lawrence James - Troyboi Vibes.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/Lawrence James - I'm Fluming.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/DJ Prashant, Jireh - Tumbiton.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/MAFX - zap.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/Lawrence James - That That That.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/Lawrence James - Conversation.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/Lawrence James - Troyboi Vibes.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/Lawrence James - I'm Fluming.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/DJ Prashant, Jireh - Tumbiton.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Move LikeThat.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Move LikeThat.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Feeling Dub.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Body.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - What They Want.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Worry Bout Them.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Lose Control Like.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Midnight Dub1.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Terry Too Much - FOREVER LOVE.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/DJ DEE ONE - AKUGBE ft Sammi Osas.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Smoke Up.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Altus - The Silent Earth.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Feeling Dub.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Body.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - What They Want.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Worry Bout Them.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Lose Control Like.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Midnight Dub1.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Terry Too Much - FOREVER LOVE.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/DJ DEE ONE - AKUGBE ft Sammi Osas.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Smoke Up.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Altus - The Silent Earth.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Lawrence James - Stay With Me.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Lawrence James - Stay With Me.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Lawrence James - See It Through My Eyes.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Lawrence James - Atmosphere.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Lawrence James - Promise.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Ed Hale - Not Like You.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Ed Da Head - Runner.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Dudi Beats - Take down the house.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Lawrence James - See It Through My Eyes.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Lawrence James - Atmosphere.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Lawrence James - Promise.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Ed Hale - Not Like You.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Ed Da Head - Runner.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Dudi Beats - Take down the house.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Roberto Marín Muñoz - I Feel Fire.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Roberto Marín Muñoz - I Feel Fire.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - Soemthing.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - Don't You.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Gab Tritone - Blunted (Original Mix).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - Good Time.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Alexyus - Bad Ass .m4a",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - Oh Lord!.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Roberto Marín Muñoz - Hold On.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Roberto Marín Muñoz - Untouchable (Extended Version).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - To The Market.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Livsey - I Wonder.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - Energy.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Verberate - Let the Rhythm Take Control (Extended Version).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - DANCEFLAW.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - Soemthing.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - Don't You.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Gab Tritone - Blunted (Original Mix).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - Good Time.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Alexyus - Bad Ass .m4a",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - Oh Lord!.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Roberto Marín Muñoz - Hold On.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Roberto Marín Muñoz - Untouchable (Extended Version).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - To The Market.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Livsey - I Wonder.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - Energy.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Verberate - Let the Rhythm Take Control (Extended Version).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - DANCEFLAW.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/Lawrence James - Know U.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/@eaDir/Lawrence James - Know U.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/@eaDir/Livsey - Rhythm.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/@eaDir/Livsey - Homage.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/@eaDir/Livsey - Greenspud.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/Livsey - Rhythm.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/Livsey - Homage.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/Livsey - Greenspud.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Garage Vibes/Lawrence James - garage ting.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Garage Vibes/@eaDir/Lawrence James - garage ting.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Garage Vibes/@eaDir/Lawrence James - Win The Game.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Garage Vibes/Lawrence James - Win The Game.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/Livsey - Past & Present.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/@eaDir/Livsey - Past & Present.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/@eaDir/ALEXYUS - IN LOVE.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/@eaDir/Livsey - Persist.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/@eaDir/Livsey & Hood Groove - Solitude (Techno Mix).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/ALEXYUS - IN LOVE.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/Livsey - Persist.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/Livsey & Hood Groove - Solitude (Techno Mix).mp3"
    ];

    var resources = [
        new AudioResource("https://getsamplefiles.com/download/m4a/sample-3.m4a", {
            :id => "id-1"
        }),
        new AudioResource("https://github.com/supermihi/pytaglib/raw/refs/heads/main/tests/data/issue46.m4a", {
            :id => "id-99"
        }),
        new AudioResource("http://192.168.1.222:8001/BBC/The_Ravers_Hour_-_Aho_Ssan_in_the_Mix_m001rrfl_original.m4a", {
            :id => "uluru-99"
        })
    ];

    for (var index = 0, max = loadedFromService.size(); index < max; index++) {
        resources.add(new AudioResource("http://192.168.1.222:8001/" + loadedFromService[index], { :id => "uluru-" + index }));
    }

function getUluruAudio() as Array<AudioResource> {
    var loadedFromService = [
        // "./Eats Everything - Radio 1's Essential Mix (2023-09-02).mp3",
        "/BBC/Mary_Anne_Hobbs_-_HAAi_with_the_ICONS_Mix_m001rz45_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Karen_Nyame_KG_with_the_ICONS_MIX_m001rrf4_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Metalheadz_30_ICONS_Mix_m001r8gm_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Sofia_Kourtesis_with_the_ICONS_Mix_m001rg4k_original.m4a",
        "./BBC/Radio_1s_Classic_Essential_Mix_-_Avalon_Emerson_2018_m001rwk1_original.m4a",
        "./BBC/Radio_1s_Classic_Essential_Mix_-_Ben_Klock_2015_m001rn8r_original.m4a",
        "./BBC/Radio_1s_Classic_Essential_Mix_-_Pan-Pot_2017_m001s35c_original.m4a",
        "./BBC/Radio_1s_Classic_Essential_Mix_-_X-Press_2_2002_m001rg0w_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_ARTBAT_m001rwrz_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Barry_Cant_Swim_m001r708_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_CamelPhat_m001q5xw_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_DJ_HEARTSTRING_m001rn58_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_DJ_Nobu_m001rfnc_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Dom_Dolla_m001qs3v_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Eats_Everything_m001prdg_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Eliza_Rose_m001qklk_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Massano_m001qcr0_original.m4a",
        "./BBC/Radio_1s_Essential_Mix_-_Pangaea_m001qzws_original.m4a",
        "./BBC/Radio_1s_Residency_-_BAMBII_-_Festival_Bangers_m001plth_original.m4a",
        "./BBC/Radio_1s_Residency_-_Ben_Hemsley_at_Boardmasters_m001pr7w_original.m4a",
        "./BBC/Radio_1s_Residency_-_Carl_Cox_-_Drum_Bass_special_m000wxyv_original.m4a",
        "./BBC/Radio_1s_Residency_-_Conducta_-_Eat_my_edit_m001qkjw_original.m4a",
        "./BBC/Radio_1s_Residency_-_Conducta_-_House_and_garage_special_m001qcpc_original.m4a",
        "./BBC/Radio_1s_Residency_-_Conducta_-_Introduction_m001pxxx_original.m4a",
        "./BBC/Radio_1s_Residency_-_Conducta_-_Take_a_break_Breakbeat_special_m001q5wv_original.m4a",
        "./BBC/Radio_1s_Residency_-_DJ_Tennis_-_Dream_and_Italo_house_m001rfjt_original.m4a",
        "./BBC/Radio_1s_Residency_-_DJ_Tennis_-_Italo_disco_m001qs5y_original.m4a",
        "./BBC/Radio_1s_Residency_-_DJ_Tennis_-_Punk_and_electronic_music_m001r722_original.m4a",
        "./BBC/Radio_1s_Residency_-_DJ_Tennis_-_Synth_pop_m001qzs1_original.m4a",
        "./BBC/Radio_1s_Residency_-_I._JORDAN_at_Boardmasters_m001pr82_original.m4a",
        "./BBC/Radio_1s_Residency_-_La_La_-_All_killer_no_filler_m001qcp7_original.m4a",
        "./BBC/Radio_1s_Residency_-_La_La_-_An_introduction_m001pxxs_original.m4a",
        "./BBC/Radio_1s_Residency_-_La_La_-_Mixed_bag_m001q5ws_original.m4a",
        "./BBC/Radio_1s_Residency_-_La_La_-_The_grand_finale_m001qkjb_original.m4a",
        "./BBC/Radio_1s_Residency_-_Manuka_Honey_-_Slow_and_hardcore_m001rfk6_original.m4a",
        "./BBC/Radio_1s_Residency_-_Manuka_Honey_-_The_beginning_m001qs60_original.m4a",
        "./BBC/Radio_1s_Residency_-_Manuka_Honey_Hybridity_m001qzs5_original.m4a",
        "./BBC/Radio_1s_Residency_-_Manuka_Honey_Sounds_from_across_the_world_m001r724_original.m4a",
        "./BBC/Radio_1s_Residency_-_Moxie_-_The_dub_mix_m001pltc_original.m4a",
        "./BBC/Radio_1s_Residency_-_Paula_Tape_-_Electronic_house_m001rxsn_original.m4a",
        "./BBC/Radio_1s_Residency_-_Paula_Tape_-_Tribal_house_m001rn3c_original.m4a",
        "./BBC/SHERELLE_-_Babes_its_jet_lag_szn_m001s2q8_original.m4a",
        "./BBC/SHERELLE_-_Deep_Dive_Loraine_James_m001rfz2_original.m4a",
        "./BBC/SHERELLE_-_Deep_Dive_Tim_Reaper_m001ryv7_original.m4a",
        "./BBC/SHERELLE_-_Eh_Wut_m001qv3d_original.m4a",
        "./BBC/SHERELLE_-_Gal_No_Worry_m001qngf_original.m4a",
        "./BBC/SHERELLE_-_No_one_does_it_like_they_do_m001r2kg_original.m4a",
        "./BBC/SHERELLE_-_Slow_It_Down_Speed_It_Up_m001r93v_original.m4a",
        "./BBC/SHERELLE_-_Sweet_Fantasy_m001rr84_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Bored_Lord_in_the_mix_m001qw54_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_C.FRIM_in_the_mix_m001r2kj_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_DJ_Storm_in_the_mix_m001rfz4_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Darwin_in_the_mix_m001s2qf_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Dinamarca_in_the_mix_m001qw5s_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_I._JORDAN_in_the_mix_m001qw58_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Luke_Vibert_as_Amen_Andrews_Halloween_Special_m001rr88_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Regal86_in_the_mix_m001r94b_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Tim_Reaper_in_the_mix_m001ryvs_original.m4a",
        "./BBC/The_Blessed_Madonna_-_See_you_ravers_on_the_radio_m001pzp3_original.m4a",
        "./BBC/The_Blessed_Madonna_-_The_Doomsday_Playlist_-_Part_1_m001pznz_original.m4a",
        "./BBC/The_Blessed_Madonna_-_The_Doomsday_Playlist_-_Part_2_m001pzp1_original.m4a",
        "./BBC/The_Ravers_Hour_-_Aho_Ssan_in_the_Mix_m001rrfl_original.m4a",
        "./BBC/The_Ravers_Hour_-_DJ_ADHD_in_the_Mix_m001qvcw_original.m4a",
        "./BBC/The_Ravers_Hour_-_Honeydrip_in_the_Mix_m001rg50_original.m4a",
        "./BBC/The_Ravers_Hour_-_Mndsgn_in_the_Mix_m001qn2k_original.m4a",
        "./BBC/The_Ravers_Hour_-_Schlachthofbronx_in_the_Mix_m001r8h2_original.m4a",
        "./BBC/The_Ravers_Hour_-_Scuba_in_the_Mix_m001r2bp_original.m4a",
        "./BBC/The_Ravers_Hour_-_patten_in_the_Mix_m001rz5n_original.m4a",
        "./BBC/The_Ravers_Hour_-_DJ_Murdadawg_in_the_Mix_m001s2sz_original.m4a",
        "./BBC/The_Ravers_Hour_-_BASHKKA_in_the_Mix_m001sdkn_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Moxie_with_the_ICONS_Mix_m001s2s2_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_With_the_ICONS_Mix_m001sdk6_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Half_Queen_in_the_mix_m001sd9k_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_TSVI_all_production_mix_m001sn33_original.m4a",
        "./BBC/The_Ravers_Hour_-_Samizdat_in_the_Mix_m001sn6l_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Chloe_Robinson_with_the_ICONS_Mix_m001sn64_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Nick_Leon_in_the_mix_m001stwf_original.m4a",
        "./BBC/The_Ravers_Hour_-_Meg_Ward_in_the_Mix_m001st9c_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Krust_with_the_ICONS_Mix_m001st8x_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_DJ_Phil_in_the_mix_m001szxd_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_D4_D4NCE_Duck_Sauce_m001r70g_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_D4_D4NCE_J.Worra_m001rfnf_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_CRUCAST_IVY_m001rws1_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_CRUCAST_Darkzy_m001s3b8_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_CRUCAST_Skepsis_m001sb5r_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_FFRR_Aaron_Hibell_m001sjr3_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_FFRR_The_Blessed_Madonna_m001ssr2_original.m4a",
        "./BBC/The_Ravers_Hour_-_DJ_Haram_in_the_Mix_m001t0g0_original.m4a",
        "./BBC/The_Ravers_Hour_-_glue70_in_the_Mix_m001tk6w_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Stenny_with_the_ICONS_Mix_m001t0d9_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Bicep_with_the_ICONS_Mix_m001tb55_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_With_the_ICONS_Mix_m001tk6f_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_Alix_Perez_in_the_mix_m001t9v2_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_C_R_R_D_R_in_the_mix_m001tj4y_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_FFRR_Parisi_m001t0nb_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_FFRR_Kenya_Grace_m001t720_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_FFRR_Diplo_m001tk5z_original.m4a",
        "./BBC/The_Ravers_Hour_-_LOUFR_in_the_mix_m001xmvd_original.m4a",
        "./BBC/The_Ravers_Hour_-_Samurai_Breaks_in_the_mix_m001xw2z_original.m4a",
        "./BBC/The_Ravers_Hour_-_Marie_Montexier_Vinyl_Special_m001y383_original.m4a",
        "./BBC/The_Ravers_Hour_-_Son_of_Philip_in_the_mix_m001y9c3_original.m4a",
        "./BBC/The_Ravers_Hour_-_Big_Dope_P_in_the_mix_m001yh44_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Four_Tet_with_the_ICONS_Mix_m001y9bn_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Helena_Hauff_with_the_ICONS_Mix_m001yh3p_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Heavee_m001xw9m_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Nick_Leon_m001y31z_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_SONIKKU_m001y95b_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Machinedrum_m001ygsm_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Manuka_Honey_m001yr3m_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Defected_Records_Darius_Syrossian_Olive_F_m001ww0c_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Defected_Records_Monki_m001x39m_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Defected_Records_YOURS_m001xbrf_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Drumsheds_Prospa_m001xkf2_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Drumsheds_Ben_Hemsley_m001xsw9_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Drumsheds_Airrica_m001y09l_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Drumsheds_SYREETA_m001y6mn_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Anjunabeats_Above_Beyond_m001ydv7_original.m4a",
        "./BBC/The_Ravers_Hour_-_sideproject_in_the_mix_m0021c1d_original.m4a",
        "./BBC/The_Ravers_Hour_-_Facta_in_the_mix_m0021hvj_original.m4a",
        "./BBC/The_Ravers_Hour_-_All_Points_East_Special_m0021q2t_original.m4a",
        "./BBC/The_Ravers_Hour_-_Leevisa_in_the_Mix_m0021wmx_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_SBTRKT_m0021jnk_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Melle_Brown_m0021qyt_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Stones_Taro_m0021y0j_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_MJ_Cole_m00221b7_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Glastonbury_2024_Eats_Everything_B2B_Groove_Armada_m0020fl6_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Glastonbury_2024_Enzo_Siragusa_m0020mrm_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Glastonbury_2024_Friction_B2B_K_Motionz_m0020vh6_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Glastonbury_2024_ALISHA_B2B_Archie_Hamilton_m00212bw_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Ibiza_2024_LF_System_m00218lh_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Ibiza_2024_TSHA_m0021frl_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Ibiza_2024_Mousse_T._m0021mnw_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Ibiza_2024_Andrea_Oliva_B2B_John_Summit_m0021tpc_original.m4a",
        "./BBC/The_Ravers_Hour_-_Violence_Gratuite_in_the_Mix_m00221mf_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Catching_Cairo_m00228q9_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Ibiza_2024_Horse_Meat_Disco_m002251x_original.m4a",
        "./BBC/The_Ravers_Hour_-_DJ_Stingray_313_In_The_Mix_m00228t8_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_VXRGO_m0022hn9_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Fabric_p-rallel_m00229hg_original.m4a",
        "./BBC/The_Ravers_Hour_-_Martyn_Bootyspoon_in_the_mix_m0022hx6_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Lara_Jones_with_the_ICONS_Mix_m0022hwr_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Ivy_Lab_m0022pyh_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Fabric_Yung_Singh_m0022hw9_original.m4a",
        "./BBC/The_Ravers_Hour_-_Avneesh_in_the_mix_m0022q87_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Kloke_m00230dc_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Fabric_Peach_m0022s31_original.m4a",
        "./BBC/The_Ravers_Hour_-_Low_End_Activist_in_the_mix_m0022zrf_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Djrum_with_the_ICONS_Mix_m0022zqz_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Madam_X_m00234g5_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Fabric_Terry_Francis_m0022xxg_original.m4a",
        "./BBC/The_Ravers_Hour_-_Maroki_in_the_Mix_m00234mg_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Ariel_Zetina_m0023fyx_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Timewarp_Nina_Kraviz_m002360h_original.m4a",
        "./BBC/The_Ravers_Hour_-_fka.m4a_in_the_mix_m0023f86_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_DJ_Oblig_m0023nzl_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Time_Warp_Sven_Vath_m0023d20_original.m4a",
        "./BBC/The_Ravers_Hour_-_Nego0_in_the_mix_m0023p8b_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Kelly_Lee_Owens_with_the_ICONS_Mix_m0023p7w_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Byrell_The_Great_m0023w5r_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Time_Warp_Mochakk_m0023lrw_original.m4a",
        "./BBC/The_Ravers_Hour_-_Isaka_in_the_Mix_m0023wbq_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Quiet_Husband_with_the_ICONS_Mix_m0023wb8_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Spooky_Bizzle_m00245rm_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Time_Warp_Clara_Cuve_m0023tms_original.m4a",
        "./BBC/The_Ravers_Hour_-_Etch_in_the_Mix_m00245y9_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_dBridge_with_the_ICONS_Mix_m00245xv_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Sam_Binga_m0024fvt_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Aus_Music_Amy_Dabbs_m00242pt_original.m4a",
        "./BBC/The_Ravers_Hour_-_Bell_Curve_in_the_Mix_m0024dx8_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Adam_F_with_the_ICONS_Mix_m0024dwt_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Aus_Music_Quantic_m0024cfg_original.m4a",
        "./BBC/The_Ravers_Hour_-_DNGDNGDNG_in_the_mix_m0024mdq_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_EMA_with_the_ICONS_Mix_m0024md8_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Chippy_Nonstop_m0024m8z_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Conducta_m0024xhm_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Aus_Music_Dam_Swindle_m0024kk4_original.m4a",
        "./BBC/The_Ravers_Hour_-_Erotic_Cafe_in_the_mix_m0024wwc_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Mantra_with_the_ICONS_Mix_m0024wvx_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Ell_Murphy_m002556d_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Aus_Music_Cinthie_m0024xdb_original.m4a",
        "./BBC/The_Ravers_Hour_-_Sakura_Tsuruta_in_the_mix_m00254t2_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Aus_Music_Will_Saul_m002523j_original.m4a",
        "./BBC/The_Ravers_Hour_-_Rose_Again_in_the_mix_m0025c8z_original.m4a",
        "./BBC/The_Ravers_Hour_-_Madison_Willing_in_the_mix_m0025lk5_original.m4a",
        "./BBC/The_Ravers_Hour_-_Toms_Extended_Yuletide_Mix_m0025tdq_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Radioactive_Man_with_the_ICONS_Mix_m0025c8j_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Pet_Shop_Boys_with_the_ICONS_Mix_m0025ljq_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Flore_m0025cwk_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_TYGAPAW_m0025mtx_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Emerald_m0025w45_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Jeremiah_Asiamah_m002628n_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Helix_Records_edd_m00258nr_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_UKF_15_Years_m0025jms_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Good_Company_ZDS_and_Jess_Bays_m0025r79_original.m4a",
        "./BBC/The_Ravers_Hour_-_Legowelt_in_the_mix_m00262sm_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_Anjunabeats_Amy_Wiles_m001yw0s_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Kia_m00262qr_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Pricila_Diaz_m00262qt_original.m4a",
        "./BBC/The_Ravers_Hour_-_Coco_Em_m0026b76_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Pete_Cannon_m00269vb_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_livwutang_m00267c1_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Tatyana_Jane_m00267c3_original.m4a",
        "./BBC/The_Ravers_Hour_-_TSVI_in_the_mix_m0026l4p_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_Lukid_m0026kr2_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_-_with_CCL_m0026mk2_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_MJK_m0026l1x_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Spectral_m0026l1z_original.m4a",
        "./BBC/The_Ravers_Hour_-_Nocow_in_the_mix_m0026scl_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Tips_for_2025_-_Bun_Xapa_m0026s9q_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Tips_for_2025_-_Hardt_Antoine_m0026s9s_original.m4a",
        "./BBC/The_Ravers_Hour_-_KUCKA_in_the_mix_m00270m0_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_with_Fabio_Grooverider_m0026wgt_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_with_Fabio_Grooverider_m0027546_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Tips_for_2025_-_Azzecca_m00270n1_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_DJ_Mag_Tips_for_2025_-_Minna-no-kimochi_m00270n3_original.m4a",
        "./BBC/The_Ravers_Hour_-_Muadeep_in_the_mix_m00275h4_original.m4a",
        "./BBC/Mary_Anne_Hobbs_-_Blawan_with_the_ICONS_Mix_m00275gp_original.m4a",
        "./BBC/SHERELLE_-_The_Sweatbox_with_HAAi_m0027bx7_original.m4a",
        "./BBC/Radio_1_Dance_Presents_-_POSITIVA_Alex_Wann_m00273yx_original.m4a",
        "./eventually-acid-peng.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - Imagination.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - Imagination.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - My Lyf.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - Conflict VIP.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - Switch Down.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - Tutorial.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/@eaDir/Livsey - Ease The Pain VIP.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - My Lyf.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - Conflict VIP.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - Switch Down.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - Tutorial.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Bassline & Bass House/Livsey - Ease The Pain VIP.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/In My Arms ( Acapella ).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/In My Arms ( Acapella ).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Atmosphere (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Conversation (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Win The Game ( Acapella ).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Move LikeThat (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Energy (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/See It Through My Eyes (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Body (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Worry Bout Them (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/That That That (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/@eaDir/Stay With Me (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Atmosphere (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Conversation (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Win The Game ( Acapella ).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Move LikeThat (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Energy (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/See It Through My Eyes (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Body (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Worry Bout Them (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/That That That (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Acapellas/Stay With Me (Acapella).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/Lawrence James - Hold You In My Arms.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/Lawrence James - Hold You In My Arms.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/MAFX - zap.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/Lawrence James - That That That.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/Lawrence James - Conversation.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/Lawrence James - Troyboi Vibes.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/Lawrence James - I'm Fluming.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/@eaDir/DJ Prashant, Jireh - Tumbiton.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/MAFX - zap.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/Lawrence James - That That That.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/Lawrence James - Conversation.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/Lawrence James - Troyboi Vibes.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/Lawrence James - I'm Fluming.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Pop & Mainstream/DJ Prashant, Jireh - Tumbiton.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Move LikeThat.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Move LikeThat.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Feeling Dub.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Body.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - What They Want.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Worry Bout Them.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Lose Control Like.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Midnight Dub1.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Terry Too Much - FOREVER LOVE.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/DJ DEE ONE - AKUGBE ft Sammi Osas.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Lawrence James - Smoke Up.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/@eaDir/Altus - The Silent Earth.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Feeling Dub.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Body.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - What They Want.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Worry Bout Them.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Lose Control Like.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Midnight Dub1.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Terry Too Much - FOREVER LOVE.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/DJ DEE ONE - AKUGBE ft Sammi Osas.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Lawrence James - Smoke Up.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Hip Hop, Trap, Afrobeats/Altus - The Silent Earth.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Lawrence James - Stay With Me.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Lawrence James - Stay With Me.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Lawrence James - See It Through My Eyes.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Lawrence James - Atmosphere.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Lawrence James - Promise.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Ed Hale - Not Like You.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Ed Da Head - Runner.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/@eaDir/Dudi Beats - Take down the house.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Lawrence James - See It Through My Eyes.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Lawrence James - Atmosphere.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Lawrence James - Promise.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Ed Hale - Not Like You.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Ed Da Head - Runner.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/EDM & Dance/Dudi Beats - Take down the house.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Roberto Marín Muñoz - I Feel Fire.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Roberto Marín Muñoz - I Feel Fire.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - Soemthing.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - Don't You.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Gab Tritone - Blunted (Original Mix).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - Good Time.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Alexyus - Bad Ass .m4a",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - Oh Lord!.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Roberto Marín Muñoz - Hold On.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Roberto Marín Muñoz - Untouchable (Extended Version).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - To The Market.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Livsey - I Wonder.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - Energy.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Verberate - Let the Rhythm Take Control (Extended Version).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/@eaDir/Lawrence James - DANCEFLAW.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - Soemthing.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - Don't You.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Gab Tritone - Blunted (Original Mix).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - Good Time.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Alexyus - Bad Ass .m4a",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - Oh Lord!.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Roberto Marín Muñoz - Hold On.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Roberto Marín Muñoz - Untouchable (Extended Version).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - To The Market.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Livsey - I Wonder.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - Energy.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Verberate - Let the Rhythm Take Control (Extended Version).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/House/Lawrence James - DANCEFLAW.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/Lawrence James - Know U.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/@eaDir/Lawrence James - Know U.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/@eaDir/Livsey - Rhythm.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/@eaDir/Livsey - Homage.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/@eaDir/Livsey - Greenspud.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/Livsey - Rhythm.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/Livsey - Homage.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/D&B/Livsey - Greenspud.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Garage Vibes/Lawrence James - garage ting.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Garage Vibes/@eaDir/Lawrence James - garage ting.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Garage Vibes/@eaDir/Lawrence James - Win The Game.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Garage Vibes/Lawrence James - Win The Game.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/Livsey - Past & Present.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/@eaDir/Livsey - Past & Present.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/@eaDir/ALEXYUS - IN LOVE.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/@eaDir/Livsey - Persist.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/@eaDir/Livsey & Hood Groove - Solitude (Techno Mix).mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/ALEXYUS - IN LOVE.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/Livsey - Persist.mp3",
        "./DJ/CROSSFADER MUSIC PACK (2021)/Techno/Livsey & Hood Groove - Solitude (Techno Mix).mp3"
    ];

    var resources = [
        new AudioResource("https://getsamplefiles.com/download/m4a/sample-3.m4a", {
            :id => "id-1"
        }),
        new AudioResource("https://github.com/supermihi/pytaglib/raw/refs/heads/main/tests/data/issue46.m4a", {
            :id => "id-99"
        })
    ];

    for (var index = 0, max = loadedFromService.size(); index < max; index++) {
        resources.add(new AudioResource("http://192.168.1.222:8001/" + loadedFromService[index], { :id => "uluru-" + index }));
    }

    return resources;
}